export const dev = window.location.origin.includes('localhost')
export const baseURL = dev ? 'http://localhost:3000' : ''
export const useSockets = false
export const domain = ''
export const clientId = ''
export const audience = ''
export const supabaseUrl = 'https://uoxkuoksvnbowxkngjfv.supabase.co'
export const supabasePublicKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVveGt1b2tzdm5ib3d4a25namZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2NzM5OTI0NzUsImV4cCI6MTk4OTU2ODQ3NX0.eASvd_GyArE73HAMywcIPDUD7CAJsfUqlWE0RCNaZo4'
export const supaPrivatKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVveGt1b2tzdm5ib3d4a25namZ2Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY3Mzk5MjQ3NSwiZXhwIjoxOTg5NTY4NDc1fQ.o2SxBv1bnEyKUX_PCibY8XqMZasy5ypgHW3W4LjbW4o'
